# Generated by Django 5.0.6 on 2024-06-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_queue_queue_type_alter_queue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='served_by_table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='ticket_number',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
